#! /usr/bin/perl

use warnings;
use strict;

my $secret_number = int(1 + rand 100);

while (chomp(my $guess = <STDIN>)) {
   if ($guess =~ /(quit|exit|^\s*$)/i || $guess == $secret_number) {
      last;
   } elsif ($guess < $secret_number) {
      print "Too low\n";
   } else {
      print "Too high\n";
   }
}
