#! /usr/bin/perl

use warnings;
no warnings 'experimental';
use strict;
use v5.14;

sub divisors
{
   my $number = shift;

   my @divisors = ();
   foreach my $divisor (2 .. ($number/2)) {
      push @divisors, $divisor unless $number % $divisor;
   }

   return @divisors;
}
my $favorite = 5;

given ($ARGV[0]) {
   when (! /\A\d+\Z/) {say "not a number"}

   my @divisors = divisors $_;

   when (2 ~~ @divisors) {say "Number is even"; continue}
   when (!(2 ~~ @divisors)) {say "Number is odd"; continue}

   when (5 ~~ @divisors) {say "Number is divisible by favorite number"; continue}
   when ($favorite) {say "Number is favorite number"; continue}
   
   my @empty;
   when (@divisors ~~ @empty) {say "Number is prime"}

   default {say "Number is divisible by @divisors"};
}
