#! /usr/bin/perl

use warnings;
no warnings 'experimental';
use strict;
use v5.14;

foreach (@ARGV) {
   when (! -e) {say "File not found"}
   when (-r) {say "$_ is readable"; continue}
   when (-w) {say "$_ is writable"; continue}
   when (-x) {say "$_ is executable"; continue}
}
