#! /usr/bin/perl

use warnings;
use strict;
use v5.14;

sub handle_sigint { exit }
sub handle_sighup { say "caught SIGHUP" }
sub handle_sigusr1 { say "caught SIGUSR1" }
sub handle_sigusr2 { say "caught SIGUSR2" }

$SIG{INT} = 'handle_sigint';
$SIG{HUP} = 'handle_sighup';
$SIG{USR1} = 'handle_sigusr1';
$SIG{USR2} = 'handle_sigusr2';
while (1) {
}
