#! /usr/bin/perl

use warnings;
use strict;

my $directory = "/";
open STDOUT, ">", "ls.out" or die "can't reopen stdout $!";
open STDERR, ">", "ls.err" or die "can't reopen stderr $!";
chdir $directory or die "$!";
system "ls", "-l";
