#! /usr/bin/perl

use warnings;
use strict;

use DateTime;
use Time::Piece;

my $t = localtime;
my $now = DateTime->new(
   year => $t->year,
   month => $t->mon,
   day => $t->mday,
);
my $date_entered = DateTime->new(
   year => $ARGV[0],
   month => $ARGV[1],
   day => $ARGV[2],
);
my $interval = $now - $date_entered;
my @interval = $interval->in_units( qw(years months days) );
printf "%d years, %d months, and %d days\n", @interval;
