#! /usr/bin/perl

use warnings;
use strict;
use File::Basename;

(my $old, my $new) = @ARGV;
(my $old_filename, my $old_dirname) = fileparse $old;
(my $new_filename, my $new_dirname) = fileparse $new;
$new = $new_dirname . $old_filename unless $new_filename;
rename $old, $new or die "failed to rename: $!";
