#! /usr/bin/perl

use warnings;

my $PI = 3.141592654;
print "Enter radius: ";
chomp(my $radius = <STDIN>);
my $circumference = 2 * $PI * $radius;
if ($radius < 0) {
   $circumference = 0;
}
print "Circumference of circle with radius $radius = $circumference\n";
