#! /usr/bin/perl

use warnings;
use strict;

my %names = (fred => 'flintstone',
             barney => 'ruble',
             wilma => 'flintstone');

print "Enter given name: ";
chomp(my $name = <STDIN>);
if (exists $names{$name}) {
   print "$name $names{$name}\n";
} else {
   print "I don't know anyone with that name.\n";
}
